{% set name = "c-blosc2" %}
{% set version = "2.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Blosc/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 90c78edcc262759dd16d243141513310624bb4fda3d98ac34dcfb78255e151c1
  patches:
    # https://github.com/Blosc/c-blosc2/pull/354
    # - 354-shared-library.diff
    # https://github.com/Blosc/c-blosc2/pull/357
    # - 357-shuffle-altivec-import.patch
    # https://github.com/Blosc/c-blosc2/pull/359
    # - 359-Find-liblz4-for-windows.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('c-blosc2') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - lz4-c
    - zstd

test:
  commands:
    - test -e $PREFIX/include/blosc2.h                    # [unix]
    - test -e $PREFIX/include/blosc2/blosc2-export.h      # [unix]
    - test -e $PREFIX/lib/libblosc2${SHLIB_EXT}           # [unix]
    - test -e $PREFIX/lib/pkgconfig/blosc2.pc             # [unix]
    - if not exist %LIBRARY_INC%\blosc2.h exit 1                # [win]
    - if not exist %LIBRARY_INC%\blosc2\blosc2-export.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\libblosc2.dll exit 1           # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\blosc2.pc exit 1     # [win]
    - if not exist %LIBRARY_LIB%\blosc2.lib exit 1.             # [win]

about:
  home: https://github.com/Blosc/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A simple, compressed, fast and persistent data store library for C

  description: |
    Next generation of C-Blosc library bringing in a new container (schunk) that can optionally be persisted (frame).  Also, more filters, codecs and other bells and whistles like pre-filter support have been added.  The API tries to be as compatible as possible with the original C-Blosc.

extra:
  recipe-maintainers:
    - FrancescAlted
    - hmaarrfk
